version: '3.5'

networks:
  es_cluster:
    name: es_cluster
    driver: bridge

services:
  elasticsearch01:
    image: ashokkumarchoppadandi/elasticsearch:7.17.0
    hostname: ${HOSTNAME}
    container_name: ${CONTAINER_NAME}
    networks:
      - es_cluster
    ports:
      - "9200:${ES_HTTP_PORT}"
      - "9300:9300"
    environment:
      HOSTNAME: ${HOSTNAME}
      ES_CLUSTER_NAME: ${ES_CLUSTER_NAME}
      ES_NODE_NAME: ${ES_NODE_NAME}
      ES_NODE_MASTER: ${ES_NODE_MASTER}
      ES_DATA_PATH: ${ES_DATA_PATH}
      ES_LOGS_PATH: ${ES_LOGS_PATH}
      ES_NETWORK_HOST: ${ES_NETWORK_HOST}
      ES_HTTP_PORT: ${ES_HTTP_PORT}
      ES_DISCOVERY_SEED_HOSTS: ${ES_DISCOVERY_SEED_HOSTS}
      ES_MASTER_NODES: ${ES_MASTER_NODES}
    ulimits:
      memlock:
        soft: -1
        hard: -1