version: '3.5'

networks:
  kafka_cluster:
    driver: bridge

services:
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    hostname: zoonavigator
    networks: 
      - kafka_cluster
    environment:
      HTTP_PORT: 8000
    restart: unless-stopped
    ports:
      - "8000:8000"

  cmak:
    image: ashokkumarchoppadandi/cmak:3.0.0.5
    container_name: cmak
    hostname: cmak
    networks: 
      - kafka_cluster
    environment:
      ZK_HOSTS: node101.dev.hdp.kafka.cnvr.net:12181
    restart: always
    ports:
      - "8080:8080"

  prometheus:
    image: ashokkumarchoppadandi/prometheus:2.32.1
    container_name: prometheus
    hostname: prometheus
    networks: 
      - kafka_cluster
    environment:
      PROMETHEUS_HOME: /usr/local/prometheus
      PROMETHEUS_HOST: prometheus
      PROMETHEUS_CONFIG_FILE: "/usr/local/prometheus/prometheus.yml"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/usr/local/prometheus/prometheus.yml:ro

  mysql-grafana:
    image: ashokkumarchoppadandi/mysql:8
    container_name: mysql-grafana
    networks:
      - kafka_cluster
    hostname: mysql-grafana
    environment:
      MYSQL_ROOT_PASSWORD: Password@123
      MYSQL_DATABASE: grafana

  grafana:
    image: ashokkumarchoppadandi/grafana:8.3.4
    container_name: grafana
    hostname: grafana
    networks: 
      - kafka_cluster
    depends_on:
      - mysql-grafana
    environment:
      DEFAULT_ADMIN_USER: admin
      DEFAULT_ADMIN_PASSWORD: admin
      HTTP_PORT: 3000
      DATABASE_TYPE: mysql
      DATABASE_HOST: "mysql-grafana:3306"
      DATABASE_NAME: grafana
      DATABASE_USER: grafana
      DATABASE_PASSWORD: grafana
    restart: always
    ports:
      - "3000:3000"
