version: '3'

networks:
  zk_cluster:
    driver: bridge

services:
  zookeeper1:
    image: ashokkumarchoppadandi/apache-zookeeper:3.6.3
    networks:
      - zk_cluster
    ports:
      - "2181:2181"
      - "7001:7000"
    hostname: zookeeper1
    environment:
      TICK_TIME: 2000
      INIT_LIMIT: 5
      SYNC_LIMIT: 2
      DATA_DIR: \/tmp\/zookeeper
      CLIENT_PORT: 2181
      MAX_CLIENT_CONNECTIONS: 0
      METRICS_PROVIDER_HTTP_PORT: 7000
      METRICS_PROVIDER_EXPORT_JVM_INFO: "true"
      QUORUM: zookeeper1,zookeeper2,zookeeper3
      ZOOKEEPER_ID: 1
    command: replicated

  zookeeper2:
    image: ashokkumarchoppadandi/apache-zookeeper:3.6.3
    networks:
      - zk_cluster
    ports:
      - "2182:2181"
      - "7002:7000"
    hostname: zookeeper2
    environment:
      TICK_TIME: 2000
      INIT_LIMIT: 5
      SYNC_LIMIT: 2
      DATA_DIR: \/tmp\/zookeeper
      CLIENT_PORT: 2181
      MAX_CLIENT_CONNECTIONS: 0
      METRICS_PROVIDER_HTTP_PORT: 7000
      METRICS_PROVIDER_EXPORT_JVM_INFO: "true"
      QUORUM: zookeeper1,zookeeper2,zookeeper3
      ZOOKEEPER_ID: 2
    command: replicated

  zookeeper3:
    image: ashokkumarchoppadandi/apache-zookeeper:3.6.3
    networks:
      - zk_cluster
    ports:
      - "2183:2181"
      - "7003:7000"
    hostname: zookeeper3
    environment:
      TICK_TIME: 2000
      INIT_LIMIT: 5
      SYNC_LIMIT: 2
      DATA_DIR: \/tmp\/zookeeper
      CLIENT_PORT: 2181
      MAX_CLIENT_CONNECTIONS: 0
      METRICS_PROVIDER_HTTP_PORT: 7000
      METRICS_PROVIDER_EXPORT_JVM_INFO: "true"
      QUORUM: zookeeper1,zookeeper2,zookeeper3
      ZOOKEEPER_ID: 3
    command: replicated
