version: '3.5'

networks:
  hadoop_cluster:
    driver: bridge

services:
  namenode:
    image: ashokkumarchoppadandi/apache-hadoop-hive:2.7.6-2.3.8-stream8
    networks:
      - hadoop_cluster
    ports:
      - "50070:50070"
    hostname: namenode
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql://mysql/metastore?createDatabaseIfNotExist=true
    command: namenode

  secondarynamenode:
    image: ashokkumarchoppadandi/apache-hadoop-hive:2.7.6-2.3.8-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
    ports:
      - "50090:50090"
    hostname: secondarynamenode
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql://mysql/metastore?createDatabaseIfNotExist=true
    command: secondarynamenode

  resourcemanager:
    image: ashokkumarchoppadandi/apache-hadoop-hive:2.7.6-2.3.8-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
    ports:
      - "8088:8088"
    hostname: resourcemanager
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql://mysql/metastore?createDatabaseIfNotExist=true
    command: resourcemanager

  historyserver:
    image: ashokkumarchoppadandi/apache-hadoop-hive:2.7.6-2.3.8-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
      resourcemanager:
        condition: service_healthy
        restart: true
    ports:
      - "19888:19888"
    hostname: historyserver
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql://mysql/metastore?createDatabaseIfNotExist=true
    command: historyserver

  mysql:
    image: ashokkumarchoppadandi/mysql:latest
    networks:
      - hadoop_cluster
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password@123
      MYSQL_DATABASE: metastore
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  hiveserver2:
    image: ashokkumarchoppadandi/apache-hadoop-hive:2.7.6-2.3.8-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
      resourcemanager:
        condition: service_healthy
        restart: true
      historyserver:
        condition: service_healthy
        restart: true
      mysql:
        condition: service_healthy
        restart: true
    ports:
      - "10002:10002"
    hostname: hiveserver2
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql://mysql/metastore?createDatabaseIfNotExist=true
    command:
      - hiveserver2

  slavenode:
    image: ashokkumarchoppadandi/apache-hadoop-hive:2.7.6-2.3.8-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
      secondarynamenode:
        condition: service_healthy
        restart: true
      resourcemanager:
        condition: service_healthy
        restart: true
      historyserver:
        condition: service_healthy
        restart: true
      hiveserver2:
        condition: service_healthy
        restart: true
    ports:
      - "18042:8042"
      - "35945:35945"
      - "4040:4040"
    hostname: slavenode
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql://mysql/metastore?createDatabaseIfNotExist=true
    command:
      - slavenode