version: '3'

networks:
  hadoop_cluster:
    driver: bridge

services:
  mysql:
    image: ashokkumarchoppadandi/mysql:latest
    networks:
      - hadoop_cluster
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password@123
      MYSQL_DATABASE: metastore

  hadoop:
    image: ashokkumarchoppadandi/apache-hadoop-hive:2.7.6-2.3.8
    networks:
      - hadoop_cluster
    depends_on:
      - mysql
    ports:
      - "50070:50070"
      - "50030:50030"
      - "8088:8088"
      - "19888:19888"
      - "18042:18042"
      - "35945:35945"
      - "4040:4040"
      - "10002:10002"
    hostname: namenode
    environment:
      FS_DEFAULT_NAME: hdfs:\/\/hadoop:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: hadoop
      HISTORY_SERVER_HOST: hadoop
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql:\/\/mysql\/metastore?createDatabaseIfNotExist=true
    command:
      - sh
      - hive