<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.bigdata.docker</groupId>
        <artifactId>DockerImages</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>CodeServer</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <docker.maven.plugin.version>0.33.0</docker.maven.plugin.version>
        <docker.container.hostname>code-server</docker.container.hostname>
        <docker.container.name>code-server</docker.container.name>
        <docker.network.mode>bridge</docker.network.mode>
        <docker.network.name>code-server-network</docker.network.name>
        <docker.container.port.mapping>8080:8080</docker.container.port.mapping>
        <docker.push.registry>docker.io</docker.push.registry>
        <docker.hub.username>REPALCE_WITH_DOCKER_HUB_USER_NAME</docker.hub.username>
        <docker.hub.password>REPALCE_WITH_DOCKER_HUB_PASSWORD</docker.hub.password>
        <docker.hub.repo.name>ashokkumarchoppadandi</docker.hub.repo.name>
        <docker.image.name>code-server</docker.image.name>
        <docker.host>0.0.0.0</docker.host>
        <docker.port>8080</docker.port>
        <docker.default.login.password>Pass@123</docker.default.login.password>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>${docker.maven.plugin.version}</version>

                <executions>
                    <execution>
                        <id>docker-build</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                            <goal>push</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <verbose>true</verbose>
                    <!-- For LINUX Environment-->
                    <!--<dockerHost>unix:///var/run/docker.sock</dockerHost>-->
                    <dockerHost>http://127.0.0.1:2375</dockerHost>

                    <!-- For Windows Environment-->
                    <!--<dockerHost>npipe:////./pipe/docker_engine</dockerHost>-->
                    <authConfig>
                        <username>${docker.hub.username}</username>
                        <password>${docker.hub.password}</password>
                    </authConfig>
                    <images>
                        <image>
                            <name>${docker.hub.repo.name}/${docker.image.name}</name>
                            <alias/>
                            <build>
                                <args>

                                </args>
                                <contextDir>${project.basedir}/src/main/docker/</contextDir>
                                <!--<assembly>
                                    <descriptorRef>artifact</descriptorRef>
                                </assembly>-->
                                <tags>
                                    <tag>${project.version}</tag>
                                    <tag>latest</tag>
                                </tags>
                            </build>

                            <run>
                                <env>
                                    <HOST>${docker.host}</HOST>
                                    <PORT>${docker.port}</PORT>
                                    <DEFAULT_LOGIN_PASSWORD>${docker.default.login.password}</DEFAULT_LOGIN_PASSWORD>
                                </env>
                                <hostname>${docker.container.hostname}</hostname>
                                <network>
                                    <mode>${docker.network.mode}</mode>
                                    <name>${docker.network.name}</name>
                                </network>
                                <ports>
                                    <port>${docker.container.port.mapping}</port>
                                </ports>
                                <containerNamePattern>${docker.container.name}</containerNamePattern>
                                <cmd>sh</cmd>
                            </run>
                        </image>
                    </images>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>