route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'SendEmailAlert'
receivers:
  - name: 'SendEmailAlert'
    email_configs:
      - to: 'test123@gmail.com'
        from: 'test123@gmail.com'
        smarthost: 'smtp.gmail.com:465'
        auth_username: 'test123@gmail.com'
        auth_identity: 'test123@gmail.com'
        auth_password: 'test123'