version: '2'

networks:
  atlas_cluster_new:
    driver: bridge

services:
  zookeepernew:
    image: ashokkumarchoppadandi/apache-kafka:2.6.1
    container_name: zookeepernew
    hostname: zookeepernew
    networks:
      - atlas_cluster_new
    ports:
      - "12182:2181"
    command: zookeeper
#    volumes:
#      - ./AtlasSetup/Zookeeper/data:/tmp/zookeeper:rw

  brokernew:
    image: ashokkumarchoppadandi/apache-kafka:2.6.1
    container_name: brokernew
    hostname: brokernew
    networks:
      - atlas_cluster_new
    ports:
      - "19093:9092"
    depends_on:
      - zookeepernew
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT:\/\/brokernew:9092
      ZOOKEEPER_CONNECT_LIST: "zookeepernew:2181"
    command: kafka
#    volumes:
#      - ./AtlasSetup/Kafka/data:/tmp/kafka-logs:rw

  mysqlnew:
    image: ashokkumarchoppadandi/mysql:latest
    container_name: mysqlnew
    networks:
      - atlas_cluster_new
    hostname: mysqlnew
    environment:
      MYSQL_ROOT_PASSWORD: Password@123
      MYSQL_DATABASE: metastore

  hadoopnew:
    image: ashokkumarchoppadandi/apache-hadoop-hive-with-atlas:2.7.6-2.3.8-2.2.0
    container_name: hadoopnew
    hostname: hadoopnew
    networks:
      - atlas_cluster_new
    ports:
      - "50071:50070"
      - "50031:50030"
      - "18089:8088"
      - "19889:19888"
      - "18043:18042"
      - "35946:35945"
      - "14041:4040"
      - "10003:10002"
    depends_on:
      - mysqlnew
    environment:
      FS_DEFAULT_NAME: hdfs:\/\/hadoopnew:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: hadoopnew
      HISTORY_SERVER_HOST: hadoopnew
      JAVAX_JDO_OPTION_CONNECTIONURL: jdbc:mysql:\/\/mysqlnew\/metastore?createDatabaseIfNotExist=true
      HIVE_AUX_JARS_PATH_FOR_ATLAS: \/opt\/apache-atlas\/hook\/hive
      HBASE_TABLE: apache_atlas_janus
      ZK_QUORUM: zookeepernew:2181
      KAFKA_BOOTSTRAP_SERVERS: brokernew:9092
      ATLAS_HOSTNAME: atlasnew
    command:
      - sh
      - atlashive
#    volumes:
#      - ./AtlasSetup/Hadoop/data:/usr/local/hadoop/data:rw

  hbasenew:
    image: ashokkumarchoppadandi/apache-hbase:2.4.9
    container_name: hbasenew
    hostname: hbasenew
    networks:
      - atlas_cluster_new
    ports:
      - "16011:16010"
      - "16031:16030"
    depends_on:
      - zookeepernew
      - hadoopnew
    environment:
      HBASE_ROOT_DIR: hdfs:\/\/hadoopnew:9000\/hbase
      HBASE_CLUSTER_DISTRIBUTED: "true"
      ZOOKEEPER_QUORUM: zookeepernew:2181
    command:
      - distributed
      - all

  solrnew:
    image: ashokkumarchoppadandi/apache-solr:8.11.1
    container_name: solrnew
    hostname: solrnew
    networks:
      - atlas_cluster_new
    ports:
      - "18983:8983"
    depends_on:
      - zookeepernew
    environment:
      MEMORY: 1g
      ZOOKEEPER_QUORUM: zookeepernew:2181
      SOLR_PORT: 8983
    command:
      - cloud
#    volumes:
#      - ./AtlasSetup/Solr/userfiles:/var/solr-home/userfiles:rw
#      - ./AtlasSetup/Solr/filestore:/var/solr-home/filestore:rw

  atlasnew:
    image: ghcr.io/hritvikpatel4/apache-atlas:master
    container_name: atlasnew
    hostname: atlasnew
    networks:
      - atlas_cluster_new
    ports:
      - "21001:21000"
    depends_on:
      - zookeepernew
      - brokernew
      - hadoopnew
      - hbasenew
      - solrnew
    environment:
      HBASE_TABLE: apache_atlas_janus
      ZK_QUORUM: zookeepernew:2181
      KAFKA_BOOTSTRAP_SERVERS: brokernew:9092
      HOSTNAME: atlasnew
      SOLR_HOST: solrnew
      SOLR_PORT: 8983
    command: cold_start
