version: '3.5'

networks:
  kafka_es_cluster:
    name: kafka_es_cluster
    driver: bridge

services:
  zookeeper:
    image: ashokkumarchoppadandi/confluent-kafka:5.5.3
    container_name: zookeeper
    networks:
      - kafka_es_cluster
    ports:
      - "2181:2181"
    hostname: zookeeper
    environment:
      ZOOKEEPER_DATA_DIR: \/tmp\/zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_MAX_CLIENT_CONNECTIONS: 0
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_ENABLE_SERVER: "false"
      ZOOKEEPER_ADMIN_SERVER_PORT: 8080
    command:
      - zookeeper
      - standalone

  broker:
    image: ashokkumarchoppadandi/confluent-kafka:5.5.3
    container_name: broker
    networks:
      - kafka_es_cluster
    depends_on:
      - zookeeper
    hostname: broker
    environment:
      BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT:\/\/0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT:\/\/broker:9092
      NUM_NETWORK_THREADS: 3
      NUM_IO_THREADS: 8
      SOCKET_SEND_BUFFER_BYTES: 102400
      SOCKET_RECEIVE_BUFFER_BYTES: 102400
      SOCKET_REQUEST_MAX_BYTES: 104857600
      LOG_DIRS: \/tmp\/kafka-logs
      NUM_PARTITIONS: 1
      NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      TRANSACTION_STATE_LOG_MIN_ISR: 1
      LOG_RETENTION_HOURS: 168
      LOG_SEGMENT_BYTES: 1073741824
      LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      ZOOKEEPER_CONNECT_LIST: "zookeeper:2181"
      ZOOKEEPER_CONNECTION_TIMEOUT_MS: 18000
      GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    command: kafka

  elasticsearch01:
    image: ashokkumarchoppadandi/elasticsearch:7.17.0
    hostname: elasticsearch01
    container_name: elasticsearch01
    networks:
      - kafka_es_cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      HOSTNAME: elasticsearch01
      ES_CLUSTER_NAME: my-elasticsearch
      ES_NODE_NAME: elasticsearch01
      ES_NODE_MASTER: "true"
      ES_DATA_PATH: "/usr/local/elasticsearch/data/"
      ES_LOGS_PATH: "/usr/local/elasticsearch/logs/"
      ES_NETWORK_HOST: 0.0.0.0
      ES_HTTP_PORT: 9200
      ES_BOOTSTRAP_MEMORY_LOCK: "false"
      ES_DISCOVERY_SEED_HOSTS: elasticsearch01
      ES_MASTER_NODES: elasticsearch01
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash01:
    image: ashokkumarchoppadandi/logstash:7.17.0
    hostname: logstash01
    container_name: logstash01
    depends_on:
      - elasticsearch01
    networks:
      - kafka_es_cluster
    environment:
      LOGSTASH_CONFIG_FILE: "logstash_kafka_spark_structured_streaming_metrics.config"
    volumes:
      - ./Logstash/src/main/docker/configs/logstash_kafka_spark_structured_streaming_metrics.config:/usr/local/logstash/config/logstash_kafka_spark_structured_streaming_metrics.config:ro
      - ./Logstash/src/main/docker/input-data:/home/logstash/input-data:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana01:
    image: ashokkumarchoppadandi/kibana:7.17.0
    hostname: kibanahost1
    container_name: kibanahost1
    depends_on:
      - elasticsearch01
    networks:
      - kafka_es_cluster
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch01:9200"]'
      KIBANA_SERVER_PORT: 5601
      KIBANA_SERVER_HOST: 0.0.0.0
      KIBANA_SERVER_NAME: kibanahost1