apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
  selector:
    name: {{ .Release.Name }}
