# Default values for hello-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configmap:
  app:
    version: v1

replicaCount: 3

image:
  repository: ashokkumarchoppadandi/hello-spring-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.0"

service:
  type: ClusterIP
  port: 8080
  portName: http

ingress:
  enabled: false
  className: "nginx"
  hosts:
    host: kubernetes.docker.internal
    port: 8080
    paths:
      path: /
      pathType: Prefix

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 1
    memory: 256Mi
