version: '3'

networks:
  prometheus_cluster:
    driver: bridge

services:
  prometheus:
    image: ashokkumarchoppadandi/prometheus:2.32.1
    container_name: prometheus
    hostname: prometheus
    networks:
      - prometheus_cluster
    environment:
      PROMETHEUS_HOME: /usr/local/prometheus
      PROMETHEUS_HOST: prometheus
      PROMETHEUS_PORT: 9090
      PROMETHEUS_CONFIG_FILE: /usr/local/prometheus/prometheus.yml
      PROMETHEUS_DATA_DIR: /usr/local/prometheus/data
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/usr/local/prometheus/prometheus.yml:ro