version: '3'

networks:
  kafka_cluster:
    driver: bridge

services:
  zookeeper:
    image: ashokkumarchoppadandi/apache-kafka:2.6.1
    networks:
      - kafka_cluster
    ports:
      - "2181:2181"
    hostname: zookeeper
    environment:
      ZOOKEEPER_DATA_DIR: \/tmp\/zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_MAX_CLIENT_CONNECTIONS: 0
      ZOOKEEPER_ENABLE_SERVER: false
      ZOOKEEPER_ADMIN_SERVER_PORT: 8080
    command: zookeeper

  broker:
    image: ashokkumarchoppadandi/apache-kafka:2.6.1
    networks:
      - kafka_cluster
    depends_on:
      - zookeeper
    hostname: broker
    environment:
      BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT:\/\/0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT:\/\/broker:9092
      NUM_NETWORK_THREADS: 3
      NUM_IO_THREADS: 8
      SOCKET_SEND_BUFFER_BYTES: 102400
      SOCKET_RECEIVE_BUFFER_BYTES: 102400
      SOCKET_REQUEST_MAX_BYTES: 104857600
      LOG_DIRS: \/tmp\/kafka-logs
      DEFAULT_PARTITIONS: 1
      NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      TRANSACTION_STATE_LOG_MIN_ISR: 1
      LOG_RETENTION_HOURS: 168
      LOG_SEGMENT_BYTES: 1073741824
      LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      ZOOKEEPER_CONNECT_LIST: "zookeeper:2181"
      ZOOKEEPER_CONNECTION_TIMEOUT_MS: 18000
      GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    command: kafka
  connect:
    image: ashokkumarchoppadandi/apache-kafka:2.6.1
    networks:
      - kafka_cluster
    depends_on:
      - zookeeper
      - broker
    hostname: connect
    environment:
      BOOTSTRAP_SERVERS: "broker:9092"
      GROUP_ID: connect-cluster
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: true
      VALUE_CONVERTER_SCHEMAS_ENABLE: true
      OFFSET_STORAGE_TOPIC: connect-offsets
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_PARTITIONS: 25
      CONFIG_STORAGE_TOPIC: connect-configs
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_TOPIC: connect-status
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_PARTITIONS: 5
      OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_HOST: 0.0.0.0
      CONNECT_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST: connect
      CONNECT_REST_ADVERTISED_PORT: 8083
      PLUGIN_PATH: \/usr\/local\/kafka\/libs
    ports:
      - "8083:8083"
    command: connect