## Setting up Ingress Controller Resource in Local - Docker Desktop for Windows

## helm upgrade \
##  --install ingress-nginx ingress-nginx \
##  --repo https://kubernetes.github.io/ingress-nginx \
##  --namespace ingress-nginx \
##  --create-namespace

apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-configmap
  labels:
    name: hello-configmap
data:
  APP_VERSION1: v1
  APP_VERSION2: v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: hello-app
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-container
        image: ashokkumarchoppadandi/hello-spring-app:v2.0
        ports:
          - containerPort: 8080
            protocol: TCP
            name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          periodSeconds: 2
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "1"
            memory: "256Mi"
        env:
          - name: APP_VERSION
            valueFrom:
              configMapKeyRef:
                name: hello-configmap
                key: APP_VERSION2

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  # type: NodePort
  selector:
    app: hello-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 30090

---
 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-ingress
  # namespace: ingress-nginx 
spec:
  ingressClassName: nginx
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - backend:
          service: 
            name: hello-service
            port:
              number: 8080
        path: /
        pathType: Prefix