apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-app
  labels:
    name: hello-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-spring-app
  template:
    metadata:
      labels:
        name: hello-spring-app
    spec:
      containers:
        - name: hello-spring-container
          image: ashokkumarchoppadandi/hello-spring-app:v1.0
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 2
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: hello-spring-app-config-map
                  key: APP_VERSION1
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-spring-app-config-map
data:
  APP_VERSION1: v1
  APP_VERSION2: v2

---
apiVersion: v1
kind: Service
metadata:
  name: hello-spring-app-service
spec:
  type: NodePort
  selector:
    name: hello-spring-app
  ports:
    - name: app-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
