version: '3.5'

networks:
  spring-network:
    driver: bridge
    name: spring-network

services:
  spring-app1:
    image: ashokkumarchoppadandi/hello-spring-app:v1.0
    container_name: spring-app1
    hostname: spring-app1
    networks:
      - spring-network
    ports:
      - "8081:8080"
    environment:
      HOSTNAME: spring-app1
      APP_VERSION: v1

  spring-app2:
    image: ashokkumarchoppadandi/hello-spring-app:v2.0
    container_name: spring-app2
    hostname: spring-app2
    networks:
      - spring-network
    ports:
      - "8082:8080"
    environment:
      HOSTNAME: spring-app2
      APP_VERSION: v2

