FROM openjdk:8

MAINTAINER AshokKumarChoppadandi ashokkumar98778@gmail.com

WORKDIR /

COPY maven/hello-spring-v1.0.jar /

ENV APP_VERSION v1

CMD java -jar /hello-spring-v1.0.jar --app.version=$APP_VERSION