version: '3.5'

networks:
  hadoop_cluster:
    driver: bridge

services:
  namenode:
    image: ashokkumarchoppadandi/apache-hadoop:2.7.6-stream8
    networks:
      - hadoop_cluster
    ports:
      - "50070:50070"
    hostname: namenode
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
    command: namenode

  secondarynamenode:
    image: ashokkumarchoppadandi/apache-hadoop:2.7.6-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
    ports:
      - "50090:50090"
    hostname: secondarynamenode
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
    command: secondarynamenode

  resourcemanager:
    image: ashokkumarchoppadandi/apache-hadoop:2.7.6-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
    ports:
      - "8088:8088"
    hostname: resourcemanager
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
    command: resourcemanager

  historyserver:
    image: ashokkumarchoppadandi/apache-hadoop:2.7.6-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
      resourcemanager:
        condition: service_healthy
        restart: true
    ports:
      - "19888:19888"
    hostname: historyserver
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
    command: historyserver

  slavenode:
    image: ashokkumarchoppadandi/apache-hadoop:2.7.6-stream8
    networks:
      - hadoop_cluster
    depends_on:
      namenode:
        condition: service_healthy
        restart: true
      secondarynamenode:
        condition: service_healthy
        restart: true
      resourcemanager:
        condition: service_healthy
        restart: true
      historyserver:
        condition: service_healthy
        restart: true
    ports:
      - "8042:8042"
      - "35945:35945"
      - "50010:50010"
    hostname: slavenode
    restart: always
    environment:
      FS_DEFAULT_NAME: hdfs://namenode:9000
      DFS_REPLICATION: 1
      YARN_RESOURCEMANAGER_HOSTNAME: resourcemanager
      HISTORY_SERVER_HOST: historyserver
    command: slavenode
