# This is a basic workflow to help you get started with Actions

name: Docker Build and Push to Docker Hub CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checking out to develop branch.
        uses: actions/checkout@v2

      # Setting up the JDK 8
      - name: Step 2 - Setting up the JDK Version to 8
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: '8'

      # Build the Maven Project and Push the docker image to Docker Hub
      - name: Step 3 - Build the Maven Project and Push the docker image to Docker Hub
        run: |
          cd MavenDockerHelloWorld
          ls -a
          mvn clean install -Ddocker.hub.username=${{ secrets.DOCKER_HUB_USERNAME }} -Ddocker.hub.password=${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Step 4 - Build and push docker image for Apache Kafka
        run: |
          cd DockerImages
          ls -a ApacheKafka
          mvn clean install -Ddocker.hub.username=${{ secrets.DOCKER_HUB_USERNAME }} -Ddocker.hub.password=${{ secrets.DOCKER_HUB_PASSWORD }} -pl ApacheKafka

      # Runs a set of commands using the runners shell
      - name: Step 5 -
        run: |
          cd DockerImages
          ls -a ConfluentKafka
          mvn clean install -Ddocker.hub.username=${{ secrets.DOCKER_HUB_USERNAME }} -Ddocker.hub.password=${{ secrets.DOCKER_HUB_PASSWORD }} -pl ConfluentKafka
